#! /usr/bin/env ruby
begin
  require 'Win32/Console/ANSI' if RUBY_PLATFORM =~ /win32/
rescue LoadError
  raise 'You must gem install win32console to use color on Windows'
end

def main
  results = {}

  max_count = 0

  args = ARGV
  if args.size > 0
    @authors = authors = args
  else
    authors = get_authors
  end

  authors.each do |author|
    groups = get_groups_for_author author

    segments = groups.keys.sort

    results[author] = {}
    segments.each do |g|
      count = groups[g].size
      results[author][g] = count
      max_count = count if count > max_count
    end
  end

  pivoted = pivot_results(results)

  segments = pivoted.keys.sort.compact

  scaled_max = 30.0
  if scaled_max > max_count
    scaled_max = max_count
    scale = 1
  else
    scale = scaled_max / (max_count + 1)
  end
  col_width = max_count.to_s.length + 1
  col_width = 3 if col_width < 3

  empty_cell = ' ' * col_width

  plot = build_plot(segments, pivoted, scale, scaled_max)

  graph_lines = build_graph_lines(plot, segments, scale, scaled_max, col_width)

  axis = render_time_segment_axis(pivoted, col_width, authors, empty_cell)
  counts_by_person_and_time_segment = render_counts(pivoted, col_width, authors, empty_cell)

  print_author_key authors, results
  print_graph(graph_lines, axis, counts_by_person_and_time_segment, empty_cell, segments, col_width)
end

def get_groups_for_author author
  times = times_for_author author

  times.group_by do |l|
    get_time_segment(l)
  end
end

def empty_result_set
  h = {}
  (0..23).each do |hour|
    ['00', '30'].each do |minute|
      k = "#{"%02d" % hour}:#{minute}"
      h[k] = {}
    end
  end
  h
end

def times_for_author author
  lines = `git log --author='#{author}'`
  time_lines = lines.split("\n").select {|l| l =~ /^Date:/}
  times = time_lines.map {|l| l.split(' ').select {|piece| piece =~ /\d\d\:\d\d\:\d\d/} }.flatten
end

def pivot_results results
  pivoted = empty_result_set
  results.each do |author, hours|
    hours.each do |hour, times|
      pivoted[hour] ||= {}
      pivoted[hour][author] = times
    end
  end
  pivoted
end

def build_plot segments, pivoted, scale, scaled_max
  plot = 1.upto(segments.size).map do |x|
    1.upto(scaled_max).map do |y|
      ' '
    end
  end

  segments.each_with_index do |hour, x|
    pivoted[hour].each do |author, count|
      y = count * scale
      y = find_empty_cell(plot, x, y, scaled_max)

      plot[x][y] = get_point(author)
    end
  end
  plot
end

def find_empty_cell plot, x, y, scaled_max
  return y  if (plot[x][y] == ' ')

  direction = 15 <=> y
  direction = 1 if direction == 0
  while plot[x][y] != ' ' && y >= 0 && y <= scaled_max
    y = y + direction
  end

  y
end

def  build_graph_lines(plot, segments, scale, scaled_max, col_width)
  graph = 1.upto(scaled_max).map do |y|
    line = 1.upto(segments.count).map do |x|
      plot[x-1][y-1] * col_width
    end

    "% #{col_width}d" % (y/scale) + ' ' + line.join('')
  end
end

def print_graph(graph_lines, axis, counts_by_person_and_time_segment, empty_cell, segments, col_width)
  graph_lines.reverse.each {|line| puts line}

  puts empty_cell + ' ' + axis
  puts empty_cell + ' ' + ('-' * (segments.length * col_width))
  puts  counts_by_person_and_time_segment.join("\n")

end

def render_time_segment_axis(pivoted, col_width, authors, empty_cell)
  axis = ''
  counts = ['   '] * authors.length

  pivoted.keys.sort.each do |segment|
    if segment[3..4] == '00'
      axis += colorize(segment[0..1],32)
    else
      axis += colorize(segment[3..4], 33)
    end
    axis += (' ' * (col_width -2))
  end
  axis
end

def render_counts(pivoted, col_width, authors, empty_cell)
  counts = ['   '] * authors.length

  pivoted.keys.sort.each do |segment|
    authors = pivoted[segment].keys.sort_by do |author|
      pivoted[segment][author]
    end.reverse

    0.upto(authors.size - 1) do |i|
      counts[i] += colorize("% #{col_width}d" % pivoted[segment][authors[i]], get_color(authors[i]))
    end
    authors.size.upto(counts.length - 1) do |i|
      counts[i] +=empty_cell
    end
  end
  counts
end

def get_authors
  all = `git shortlog`.split("\n").select {|line| line =~ /\(\d+\):$/}
  parsed = all.map do |line|
    pos = line.rindex('(')
    {
      :name => line[0..(pos - 2)],
      :count => line[(pos +1)...-2].to_i
    }
  end
  sorted = parsed.sort_by {|a| -a[:count]}
  top_5 = sorted[0..4]
  @authors = top_5.map {|a| a[:name]}
end

def print_author_key authors, results
  authors.each {|author| puts colorize("#{author} #{results[author].values.reduce{|a,b| a+b}}",  get_color( author )) }
end

def get_time_segment time
  minutes_per_segment = 30
  pieces = time.split(':')
  hour = pieces.first
  minute = (pieces[1].to_i / minutes_per_segment).to_i * minutes_per_segment

  "#{hour}:#{'%02d' % minute}"
end

def get_background_color author
  colors = [41,42,43,44,45,46]
  get_color_escape(colors, author)
end

def get_color author
  colors = [31,32,33,34,35,36]
  get_color_escape colors, author
end

def get_color_escape colors, author
  index = @authors.index(author) rescue 0
  color = colors[index % colors.length]
end

def get_point author
  colorize(" ", get_background_color( author ))
end

def colorize(text, color_code)
  "\e[#{color_code}m#{text}\e[0m"
end

main
